name: menta-plexmediaserver
version: 1.5.6.3790-4613ce077
summary: Unofficial snap for the Plex media server for the amd64 architecture
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/

apps:

  server:
    command: bin/server.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - removable-media

confinement: strict
grade: stable

parts:

  server:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/1.5.6.3790-4613ce077/plexmediaserver_1.5.6.3790-4613ce077_amd64.deb

  server-configurations:
    plugin: dump
    prime:
      - bin/server.sh
