name: menta-plexmediaserver
version: 1.8.3.4235
summary: Unofficial snap for the Plex media server for the amd64 architecture
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/

apps:

  server:
    command: bin/server.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - removable-media

confinement: strict
grade: stable

parts:

  server:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/1.8.3.4235-2d20185b0/plexmediaserver_1.8.3.4235-2d20185b0_amd64.deb
    install: |
      rm -f etc/init.d/plexmediaserver
      rm -f ../install/etc/init.d/plexmediaserver

  server-configurations:
    plugin: dump
    prime:
      - bin/server.sh
