name: menta-plexmediaserver
version: 1.10.1.4602
summary: Unofficial snap for the Plex media server for the amd64 architecture
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/

apps:

  server:
    command: bin/server.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - removable-media
      - home

confinement: strict
grade: stable

parts:

  server:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/1.10.1.4602-f54242b6b/plexmediaserver_1.10.1.4602-f54242b6b_amd64.deb
    source-type: deb
    prepare: |
      rm -f etc/init.d/plexmediaserver

  server-configurations:
    plugin: dump
    prime:
      - bin/server.sh
